dist: focal

language: c
sudo: false
compiler:
  - gcc
  - clang

before_install:
  - sudo apt update && sudo apt install -y libc6-dbg

script:
  - ./autogen.sh && ./configure && make && make check
  - perl tests/vg_regtest pmemcheck
